# Generated by Django 4.1.2 on 2022-10-30 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='EmployeeWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.userprofile')),
            ],
        ),
    ]
