# Generated by Django 4.1.2 on 2022-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_userprofile_qrcode_employeeworkinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('Software Enginnering', 'Software Enginnering'), ('Data Scientist', 'Data Scientist'), ('HR', 'HR'), ('Software Testing', 'Software Testing'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Cloud Enginnering', 'Cloud Enginnering')], max_length=120)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employe_role',
            field=models.CharField(choices=[('Software Enginnering', 'Software Enginnering'), ('Data Scientist', 'Data Scientist'), ('HR', 'HR'), ('Software Testing', 'Software Testing'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Cloud Enginnering', 'Cloud Enginnering')], default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeworkinghours',
            name='start_time',
            field=models.DateTimeField(blank=True, default='0:00:00', null=True),
        ),
    ]
