# Generated by Django 4.1.2 on 2022-11-11 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_userprofile_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_logout',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.userprofile')),
            ],
        ),
    ]
