# Generated by Django 4.1.2 on 2022-11-11 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_remove_profile_logout_time_userprofile_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 11, 9, 51, 18, 822870, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
