# Generated by Django 4.1.2 on 2022-11-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_alter_userprofile_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
