# Generated by Django 4.1.2 on 2022-11-14 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_alter_userprofile_logout_time_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmintoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('sent_time', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 20, 55, 56, 818474))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.userprofile')),
            ],
        ),
    ]
