# Generated by Django 4.1.2 on 2022-11-14 20:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employe', '0009_admintouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintouser',
            name='sent_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 20, 56, 46, 778573)),
        ),
        migrations.AlterField(
            model_name='admintouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
