# Generated by Django 4.1.2 on 2022-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0011_alter_admintouser_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintouser',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
