# Generated by Django 4.1.2 on 2022-11-21 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employe", "0013_feedback_sent_time_alter_admintouser_sent_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commanfeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Software Enginnering", "Software Enginnering"),
                            ("Data Scientist", "Data Scientist"),
                            ("HR", "HR"),
                            ("Software Testing", "Software Testing"),
                            ("Backend Developer", "Backend Developer"),
                            ("Frontend Developer", "Frontend Developer"),
                            ("Cloud Enginnering", "Cloud Enginnering"),
                        ],
                        max_length=120,
                    ),
                ),
                ("comments", models.CharField(max_length=120)),
                (
                    "sent_time",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 11, 21, 12, 35, 54, 265972),
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="admintouser",
            name="sent_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 11, 21, 12, 35, 54, 265709),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="sent_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 11, 21, 12, 35, 54, 265466),
                null=True,
            ),
        ),
    ]
